"""Add Admin and Password Fields

Revision ID: 23eaac6153ec
Revises: f14a2fc94bf7
Create Date: 2019-05-13 10:12:59.213748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23eaac6153ec'
down_revision = 'f14a2fc94bf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volunteer', sa.Column('admin', sa.Boolean(), nullable=False))
    op.add_column('volunteer', sa.Column('password', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volunteer', 'password')
    op.drop_column('volunteer', 'admin')
    # ### end Alembic commands ###
