"""Add feedback items

Revision ID: 7052c1ce164b
Revises: aced4dfe0e41
Create Date: 2019-05-19 20:56:03.646034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7052c1ce164b'
down_revision = 'aced4dfe0e41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('handled', sa.Boolean(), nullable=False))
    op.add_column('feedback', sa.Column('response', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'response')
    op.drop_column('feedback', 'handled')
    # ### end Alembic commands ###
