"""Add Alert Boolean

Revision ID: aced4dfe0e41
Revises: 23eaac6153ec
Create Date: 2019-05-19 20:26:03.681186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aced4dfe0e41'
down_revision = '23eaac6153ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volunteer', sa.Column('alert', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volunteer', 'alert')
    # ### end Alembic commands ###
