"""Add Body Text Field to Feedback

Revision ID: f14a2fc94bf7
Revises: 07df42b1e585
Create Date: 2019-05-05 15:35:25.348184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f14a2fc94bf7'
down_revision = '07df42b1e585'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('body', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'body')
    # ### end Alembic commands ###
